[package]
name = "rocket_async_compression"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "786db9b832b7edd91f143b24835677c69121a9bb" }
lazy_static = "1.4"
futures = "0.3"
tokio = { version = "=1.8.1", features = [] }

async-compression = { version = "0.3", features = ["gzip", "brotli", "tokio"] }
