[package]
name = "rocket_async_compression"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
lazy_static = "1.4.0" 
futures = "0.3.17"

async-compression = { version = "0.3.8", features = ["gzip", "brotli", "tokio"] }
